layout_spectrum: 0.7648786033969373
typography_spectrum: 0.758561402792111
color:
  saturation: 0.4104666346684098
  brandStrength: 0.050476375967264175
  lightness: 0.2923144774977118
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  rhythmicContrast: 0.6999231323134154
title: ComputerSpot
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: Where everything Computer happens
navigation:
  - name: Main Page
    url: 'http://www.computerspot.gr'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/799751ee-22cd-4b1f-ba71-f3a5e8bfd4a3.ico
author:
  name: Αλέξανδρος Ανδρούτσος
  email: alex.androutsos@gmail.com
  url: www.ComputerSpot.gr
name: ComputerSpot
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1cb0f9c2-11f6-4cd0-b501-d10ba023a263.png
